//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpRestService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeptTable
    {
        public DeptTable()
        {
            this.EmpTables = new HashSet<EmpTable>();
        }
    
        public int DeptId { get; set; }
        public string DeptName { get; set; }
    
        public virtual ICollection<EmpTable> EmpTables { get; set; }
    }
}
